apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../providers/aws

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: api.vwong.dev

images:
  - name: app
    newName: 788455525284.dkr.ecr.us-east-1.amazonaws.com/kube
    newTag: latest